### ISSUE TITLE
Bot lacks the ability to pick up where it left off

### ISSUE THREAD

**Issue by NanoCats** [mekb-turtle/pixel-canvas-bot#2]
For multiple reasons, the automation can fail. There's a big problem with that! It can fail when it's hundreds of pixels into a 100,000 pixel job! 

I had the bot get stuck error-401-ing and had to close it and restart, and to my chagrin it started again from the very beginning. Placing pixels over themselves even though they were already the same color! This basically makes it so that the bot will never be able to complete a job of even moderate size.

**Comment by sophuric** [comment]
i'm already working on this, it'll check if the pixel in the chunk is already the same pixel and skip it, chunks will be cached so we don't make thousands of useless requests
