### ISSUE TITLE
Terminal based Operating system

### ISSUE THREAD

**Issue by 0pilatos0** [mekb-turtle/pixel-canvas-bot#7]
Hi, 

I want to use my ubuntu server to draw my little projects for me, is there a way for me to grab the appCheckToken and fingerprint programmaticly? because of the ubuntu server not having Gui there is no way for me to open any devtools.

**Comment by sophuric** [comment]
if you have a browser with dev tools on another, you can use that. just download the repo, set .env file, etc on the server. the website doesn't make it easy to get a fingerprint/token programmatically unfortunately
